### ISSUE TITLE
JSON unmarshalling in generic POST handler

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/arbor#12]
https://github.com/acm-uiuc/arbor/blob/master/proxy/POST.go#L53

I'm pretty sure that this JSON unmarshalling is unintended. If a request is an XML, or form-data, the POST handler shouldn't try to unmarshal it from JSON and then re-marshal it to XML/form-data -- should just be a pass-through.

**Comment by narendasan** [comment]
Yeah this is a bug, its a simple fix if we dont want to support xml at all
