### ISSUE TITLE
Unit tests pass locally (Mac and Linux) fail on Travis

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/arbor#24]
Unit tests when run locally (within /tests ```go test```) tests pass fine. When run on travis they fail. Suspect it is due to some nuance in docker networking.

**Comment by narendasan** [comment]
@bcongdon any ideas?

**Comment by bcongdon** [comment]
Maybe try using `127.0.0.1` instead of `0.0.0.0`?

https://github.com/travis-ci/travis-ci/issues/6449#issuecomment-238907394
